### ISSUE TITLE
Not recognising tracks

### ISSUE THREAD

**Issue by turkeyphant** [hugovk/bbcscrobbler#9]
The current programme on 6music (Gilles Peterson
Joining The Musical Dots: Shuya Okino, Swindle and Muva Of Earth) isn't working. 

I just get `Last track over an hour ago, don't scrobble`.

**Comment by hugovk** [comment]
Hi, thanks for the report. The tracks come from https://www.last.fm/user/bbc6music and unfortunately sometimes the BBC stop updating it.

It's usually temporary and it's updating again now.

**Comment by hugovk** [comment]
I noticed last week and this week the BBC haven't been scrobbling Gilles Peterson's show, see the three hour gap today:

![image](https://user-images.githubusercontent.com/1324225/150650419-ec597620-0de2-44c9-a935-951af5928009.png)

https://www.last.fm/user/bbc6music

So this confirms the problem is at the BBC's side, hopefully they'll get it fixed at some point.
